# Netlify configuration file for Nara

[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Ensure all client-side URL routes redirect back to the main index.html for React SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[headers]
  [[headers.values]]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"